apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-configmap
data:
  setup.sh: |
    #!/bin/bash
    echo "Do something!"
---
apiVersion: v1
kind: Secret
metadata:
  name: sample-secret
type: Opaque
stringData:
  secret.yaml: |-
    secret: "important"
